name: CI
on: [push, pull_request]

env:
  ProjectName: SeewoHelper

jobs:
  build:

    runs-on: windows-latest
    
    env:
      NET_TFM: net5.0-windows
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      
    - name: Build
      shell: pwsh
      run: .\build.ps1
      
    - name: Upload .NET App
      continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ProjectName }}-WinNoRuntime
        path: SeewoHelper\bin\${{ env.Configuration }}\${{ env.NET_TFM }}\publish\

    - name: Upload x64
      continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ProjectName }}-Win64
        path: SeewoHelper\bin\${{ env.Configuration }}\${{ env.NET_TFM }}\win-x64\publish\

    - name: Upload x86
      continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ProjectName }}-Win32
        path: SeewoHelper\bin\${{ env.Configuration }}\${{ env.NET_TFM }}\win-x86\publish\

    - name: Package .NET App
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path C:\builtfiles -Force > $null
        7z a -mx9 "C:\builtfiles\$env:ProjectName.7z" ".\SeewoHelper\bin\$env:Configuration\$env:NET_TFM\publish\*"

    - name: Package x64
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path C:\builtfiles -Force > $null
        7z a -mx9 "C:\builtfiles\$env:ProjectName-win-x64.7z" ".\SeewoHelper\bin\$env:Configuration\$env:NET_TFM\win-x64\publish\*"

    - name: Package x86
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path C:\builtfiles -Force > $null
        7z a -mx9 "C:\builtfiles\$env:ProjectName-win-x86.7z" ".\SeewoHelper\bin\$env:Configuration\$env:NET_TFM\win-x86\publish\*"

    - name: Create a new GitHub release if a new tag is pushed
      uses: softprops/action-gh-release@v1
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        prerelease: true
        draft: false
        files: |
          C:\builtfiles\${{ env.ProjectName }}.7z
          C:\builtfiles\${{ env.ProjectName }}-win-x64.7z
          C:\builtfiles\${{ env.ProjectName }}-win-x86.7z
        body: |
          ## 更新日志
          * 这是 GitHub Action 自动化部署，更新日志将会手动更新。